apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - app-secrets.yaml
  - redis.yaml
  - postgres.yaml
  - zookeeper.yaml
  - kafka.yaml
  - product-api.yaml
  - order-consumer.yaml
  # Istio mesh policy
  - peer-authentication.yaml
  - authorization-policies.yaml
