apiVersion: v1
kind: Namespace
metadata:
  name: redis-api-infra
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-api-logging
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis-api-app
  labels:
    istio-injection: enabled
