# redis-api-infra namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: redis-api-infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: redis-api-infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper
  namespace: redis-api-infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: redis-api-infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak
  namespace: redis-api-infra
---
# redis-api-logging namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch
  namespace: redis-api-logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logstash
  namespace: redis-api-logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kibana
  namespace: redis-api-logging
---
# redis-api-app namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
  namespace: redis-api-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-consumer
  namespace: redis-api-app
