apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: redis-api
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.6.0
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            exec:
              command: [bash, -c, "echo ruok | nc localhost 2181 | grep imok"]
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: redis-api
spec:
  selector:
    app: zookeeper
  ports:
    - port: 2181
      targetPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-zookeeper
  namespace: redis-api
spec:
  selector:
    matchLabels:
      app: log-zookeeper
  template:
    metadata:
      labels:
        app: log-zookeeper
    spec:
      containers:
        - name: log-zookeeper
          image: confluentinc/cp-zookeeper:7.6.0
          ports:
            - containerPort: 2182
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2182"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            exec:
              command: [bash, -c, "echo ruok | nc localhost 2182 | grep imok"]
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: log-zookeeper
  namespace: redis-api
spec:
  selector:
    app: log-zookeeper
  ports:
    - port: 2182
      targetPort: 2182
